spring:
  datasource:
    url: ${datasource.url}
    password: ${datasource.password}
    username: ${datasource.username}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: none
    #ddl-auto: none
    properties:
      hibernate:
        highlight_sql: true
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    database: mysql
    generate-ddl: true
  #      open-in-view: false
  config:
    import: 'aws-parameterstore:'
logging:
  level:
    org.hibernate.sql: info
  #    org.hibernate.type: trace
mail:
  address:
    admin: ${admin.address}
jwt:
  key: ${jwt.key}
  access-token-expiration-minutes: 1440
  refresh-token-expiration-minutes: 1440

aws:
  paramstore:
    name: mpt
    enabled: true
    profile-separator:
    prefix: /config