cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false
spring:
  s3:
    bucket: ${s3.bucket}
    access-key: ${s3.accessKey}
    secret-key: ${s3.secretKey}
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB
  datasource:
    url: jdbc:mysql://localhost:3306/MPT
    password: 1234
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create
    #ddl-auto: none
    properties:
      hibernate:
        highlight_sql: true
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    database: mysql
    generate-ddl: true
  #      open-in-view: false
logging:
  level:
    org.hibernate.sql: info
    #    org.hibernate.type: trace
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
mail:
  address:
    admin: admin@gmail.com
jwt:
  key: zxcasdlqwealksjdioqywejkashdjkhj1k23hjkhsd87382h
  access-token-expiration-minutes: 1440
  refresh-token-expiration-minutes: 1440