name: frontci

on:
  push:
    branches:
      - fe-deploy/deploy_wan 

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@master

      - name: Cache node modules # node modules 캐싱
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-master-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Install Dependencies # 의존 파일 설치
        run: npm i
        working-directory: ./front

      - name: Build # React Build
        run: npm run build
        env:
          REACT_APP_BASE_URL: ${{ secrets.REACT_APP_BASE_URL }}
          REACT_APP_GOOGLE_LOGIN_URL: ${{ secrets.REACT_APP_GOOGLE_LOGIN_URL }}
          CI: ""
        working-directory: ./front

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.FRONT_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.FRONT_SECRET_KEY }}
        run: |
          aws s3 cp \
            --recursive \
            --region ap-northeast-2 \
            build s3://mpt-front
        working-directory: ./front
